apiVersion: "nextbreakpoint.com/v1"
kind: FlinkCluster
metadata:
  name: test-1
spec:
  pullSecrets: regcred
  pullPolicy: IfNotPresent
  flinkImage: registry:30000/flink:1.7.2
  flinkJobSpec:
    image: registry:30000/flink-jobs:1
    jarPath: /flink-jobs.jar
    className: com.nextbreakpoint.flink.jobs.TestJob
    parallelism: 1
    arguments:
      - --BUCKET_BASE_PATH
      - file:///var/tmp
  jobManagerSpec:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
  taskManagerSpec:
    serviceMode: NodePort
    storageClass: hostpath
    environment:
    - name: FLINK_GRAPHITE_HOST
      value: graphite.default.svc.cluster.local
